sudo: false
language: node_js
node_js:
  - 4
  - 6
  - 7
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
after_success:
  - npm run dist
notifications:
  irc:
    channels:
      - "chat.freenode.net#datbots"
    template:
      - "%{repository_slug} - %{commit_subject} - %{result} - %{build_url}"
    skip_join: true
    on_success: change
    on_failure: always
